### ISSUE TITLE
True.KenticoMapper vs Kentico Code Generation

### ISSUE THREAD

**Issue by TheEskhaton** [truedigital/True.KenticoMapper#1]
Hi :)

What would you say are the main advantages of using this library opposed to the kentico Code Generation feature? 

Thanks.

**Comment by TheMunro** [comment]
Hello,

The main advantage as I see it is that this library can completely disconnect you from the Kentico API. 

To my knowledge using the Kentico Code Generation API tightly couples your implementation to Kentico types since you are required to inherit from them. This means that you cannot easily mock these objects in your unit tests as they are dependent on underlying Kentico functionality.

This library simply uses a TreeNode to populate a model using reflection, it does not require your model to inherit from Kentico types.
